### ISSUE TITLE
Tried adding the mod to my Aternos server, this error pops up, how to fix?

### ISSUE THREAD

**Issue by ToxicSkullX** [Pepperoni-Jabroni/CompleteBoneMeal#1]
https://mclo.gs/nBjpBoH

**Comment by Pepperoni-Jabroni** [comment]
Ah, sorry. Please ensure you have the Cloth Config API installed as well (https://www.curseforge.com/minecraft/mc-mods/cloth-config). I need to change how the dependency is implemented to make it optional, since the config isn't strictly required for the mod to be functional.

**Comment by ToxicSkullX** [comment]
> Ah, sorry. Please ensure you have the Cloth Config API installed as well (https://www.curseforge.com/minecraft/mc-mods/cloth-config). I need to change how the dependency is implemented to make it optional, since the config isn't strictly required for the mod to be functional.

Alright that fixed it, thanks!
